version: '2'

services:

  mysql:
    command: mysqld --user=root --verbose
    build: ./docker/mysql
    volumes:
      - ./docker/.volumes/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file: ./docker/.env

  rails:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_HOME=${PWD}
    ports:
     - "3000:3000"
    command: rails s -p 3000 -b 0.0.0.0
    depends_on:
      - mysql
    links:
     - mysql
    volumes:
      - .:${PWD}
